### ISSUE TITLE
It does not work as expected on value based texts

### ISSUE THREAD

**Issue by amin79** [theLee3/flutter_auto_translator#2]
This is the text in english:

`"cancelationDay": "{count, select, 1{Free cancelation {count} day before}  other{Free cancelation {count} days before}}",`

and this is what I get when it's translated to German:

`"cancelationDay": "{count, select, 1{Kostenlose Stornierung{count} Tage vorher} other{Kostenlose Stornierung count} Tage vorher}}",`

as you see in the translated text in "other",  "count" shall be inside {} but its not. It's the same for all other languages.
it shall be {count} but it's count}

auto_translator: ^1.1.0

**Comment by theLee3** [comment]
@amin79 Please update the `auto_translator` dependency in `pubspec.yaml` to the following:

```
auto_translator:
    git: 
      url: https://github.com/theLee3/flutter_auto_translator.git
```

This will pull the 2.0.0 release candidate that I just pushed to Github. I have to update the docs and example before publishing. I would love to know if it resolves your issue.

**Comment by amin79** [comment]
Hello. Thank you for your work.
But I got following error:

Unhandled exception:
type '_Map<String, dynamic>' is not a subtype of type 'String'
#0      _buildTemplate (package:auto_translator/src/main.dart:206:53)
#1      _translate (package:auto_translator/src/main.dart:117:33)
#2      runWithArguments (package:auto_translator/src/main.dart:51:11)

**Comment by amin79** [comment]
@theLee3 I did it but still was V1. Then I deleted the .pub-cache folder and now I get this error:

Could not find a file named "pubspec.yaml" in https://github.com/theLee3/flutter_auto_translator.git

**Comment by amin79** [comment]
I tried once more and was able to get it run finally. 
Now get this error:

RangeError (index): Invalid value: Not in inclusive range 0..34: -1
#0      _StringBase.[] (dart:core-patch/string_patch.dart:258:41)
#1      Translator._removeAddedWhitespace (package:auto_translator/src/translator.dart:130:20)
#2      Translator.translate (package:auto_translator/src/translator.dart:59:15)
<asynchronous suspension>
#3      _translate (package:auto_translator/src/main.dart:168:21)
<asynchronous suspension>
#4      runWithArguments (package:auto_translator/src/main.dart:49:5)
<asynchronous suspension>

**Comment by theLee3** [comment]
> BTW. it seems that the problem I had for translation is solved in this version.

Well at least there's that! 🥳 LOL

I think I tracked down the last issue. One edge case unaccounted for.

Please run `flutter pub upgrade` and try again. Hopefully this will be the last time🤞
Ensure that the version printed to the console is 2.0.0+1.

**Comment by amin79** [comment]
Hi. I tested it. Everything works :)
Thank you for your support
